---
title: "Test Paramerized OHSS Report"
format: html
execute: 
  echo: false
  warning: false
  message: false
params:
  ctzn: "india"
editor: visual
---

```{r}
#| label: load

library(tidyverse)
library(gapminder)
library(quarto)
removals <- read.csv("dhs_removals_ctzn.csv")
admin <- read.csv("dhs_adminreturns_ctzn.csv")
enf <- read.csv("dhs_enfreturns_ctzn.csv")
ero <- read.csv("ero_arrests_ctzn.csv")
cbp1 <- read.csv('cbp1_apt_ctzn.csv')
ice_bkin <- read.csv('ice_bookins_ctzn.csv')
ice_ero <- read.csv('ice_ero_rr_ctzn.csv')
#swb_credfear <- read.csv('swborder_credfear_ctzn.csv')
options(scipen = 999)
```

```{r}
#| label: tidy and plot function

tidy_df <- function(df, ctzn){
  tidier <- df |>
    filter(month == "Total")|>
    pivot_longer(!c(fiscal_year, month), names_to = "categories" , values_to = "count") |>
    filter(categories == ctzn) |>
    mutate(count = as.numeric(count)) |>
    mutate(categories = str_to_title(categories)) |>
    rename(totals = count, `Fiscal Year` = fiscal_year)


  tidier_max <- max(tidier$totals)

  tidier_max_fy <- tidier |>
     filter(totals == tidier_max)

  tidier_max_fy <- tidier_max_fy$`Fiscal Year`
  
  fig_cond <- ifelse(nrow(tidier)>0, "all", 'none')
  res_cond <- ifelse(nrow(tidier)>0, "TRUE", "hide")


  out <- list(tidier, tidier_max, tidier_max_fy, fig_cond, res_cond)
  
}


plot_df <- function(long_df, ctzn, titler, ylabel){
  plt <- ggplot(long_df, aes(x=`Fiscal Year`, y=totals, fill=categories))+
    geom_bar(position = "stack", stat = "identity") +
    labs(title = titler)+
    ylab(ylabel)+
    scale_y_continuous(labels = scales::comma)+
    theme_minimal()+
    theme(legend.position = "none")
  plt
}

```

```{r} 
#| label: conditional processer

### Run tidy_df on each csv, if nrow>0, signal to run codeblock. Otherwise, signal to skip codeblock.
#Removals
out_removals<- tidy_df(removals, params$ctzn)
cond_removals <- unlist(out_removals[[4]])
res_removals <- unlist(out_removals[[5]])

#Admin Returns
out_admin <- tidy_df(admin, params$ctzn)
cond_admin <- unlist(out_admin[[4]])
res_admin <- unlist(out_admin[[5]])

#Enforcement Returns
out_enf <- tidy_df(enf, params$ctzn)
cond_enf <- unlist(out_enf[[4]])
res_enf <- unlist(out_enf[[5]])

#ERO Arrests
out_ero <- tidy_df(ero, params$ctzn)
cond_ero <- unlist(out_ero[[4]])
res_ero <- unlist(out_ero[[5]])

#CBP-One Appointments
out_cbp1 <- tidy_df(cbp1, params$ctzn)
cond_cbp1 <- unlist(out_cbp1[[4]])
res_cbp1 <- unlist(out_cbp1[[5]])

#ICE Book Ins
out_bkin <- tidy_df(ice_bkin, params$ctzn)
cond_bkin <- unlist(out_bkin[[4]])
res_bkin <- unlist(out_bkin[[5]])

#ICE ERO Returns and Removals
out_ice_ero <- tidy_df(ice_ero, params$ctzn)
cond_ice_ero <- unlist(out_ice_ero[[4]])
res_ice_ero <- unlist(out_ice_ero[[5]])
```

```{r, fig.keep=cond_removals, results=res_removals}
#| label: removal plot
cat(paste0("Removals of ", str_to_title(params$ctzn), " Citizens by Fiscal Year"))
df <- out_removals[[1]]
plt <- plot_df(df, params$ctzn, "DHS Removals by FY", "Removals")
max <- unlist(out_removals[[2]])
max_fy <- unlist(out_removals[[3]])
plt
cat(paste0("DHS conducted removals of ", scales::comma(max), 
           " citizens of ", 
           str_to_title(params$ctzn), 
           " from the United States in ", 
           max_fy, " the most in any fiscal year since 2014."))

```

```{r, fig.keep=cond_admin, results=res_admin}
#| label: administrative returns plot
cat(paste0("Administrative Returns of " , str_to_title(params$ctzn), " Citizens by Fiscal Year"))
df <- out_admin[[1]]
plt <- plot_df(df, params$ctzn, "DHS Administrative Returns by FY", "Returns")
max <- unlist(out_admin[[2]])
max_fy <- unlist(out_admin[[3]])
plt
cat(paste0("DHS conducted administrative returns of ", scales::comma(max), 
           " citizens of ", str_to_title(params$ctzn), 
           " from the United States in ", max_fy, 
           " the most in any fiscal year since 2014."))
```

```{r, fig.keep=cond_enf, results=res_enf}
#| label: enforcement returns plot
cat(paste0("Enforcement Returns of " , str_to_title(params$ctzn), " Citizens by Fiscal Year"))
df <- out_enf[[1]]
plt <- plot_df(df, params$ctzn, "DHS Enforcement Returns by FY", "Returns")
max <- unlist(out_enf[[2]])
max_fy <- unlist(out_enf[[3]])
plt
cat(paste0("DHS conducted enforcement returns of ", scales::comma(max), 
           " citizens of ", str_to_title(params$ctzn), 
           " from the United States in ", max_fy, 
           " the most in any fiscal year since 2014."))
```

```{r, fig.keep=cond_ero, results=res_ero}
#| label: ERO arrests plot
cat(paste0("ERO Arrests of " , str_to_title(params$ctzn), " Citizens by Fiscal Year"))
df <- out_ero[[1]]
plt <- plot_df(df, params$ctzn, "ICE ERO Arrests by FY", "Arrests")
max <- unlist(out_ero[[2]])
max_fy <- unlist(out_ero[[3]])
plt
cat(paste0("DHS conducted arrests of ", scales::comma(max), 
           " citizens of ", str_to_title(params$ctzn), 
           " from the United States in ", max_fy, 
           " the most in any fiscal year since 2014."))

```

```{r, fig.keep=cond_cbp1, results=res_cbp1}
#| label: CBP-One Appointments
cat(paste0("CBP-One Appointments of " , str_to_title(params$ctzn), " Citizens by Fiscal Year"))
df <- out_cbp1[[1]]
plt <- plot_df(df, params$ctzn, "CBP-One Appointments by FY", "Appointments")
max <- unlist(out_cbp1[[2]])
max_fy <- unlist(out_cbp1[[3]])
plt
cat(paste0("CBP opened appointments on it's CBP-One app for ", scales::comma(max), 
           " citizens of ", str_to_title(params$ctzn), 
           " from the United States in ", max_fy, 
           " the most in any fiscal year since 2023."))
```

```{r, fig.keep=cond_bkin, results=res_bkin}
#| label: ICE Book Ins
cat(paste0("ICE Book Ins of " , str_to_title(params$ctzn), " Citizens by Fiscal Year"))
df <- out_bkin[[1]]
plt <- plot_df(df, params$ctzn, "ICE Book Ins by FY", "Book Ins")
max <- unlist(out_bkin[[2]])
max_fy <- unlist(out_bkin[[3]])
plt
cat(paste0("ICE booked in ", scales::comma(max), 
           " citizens of ", str_to_title(params$ctzn), 
           " from the United States in ", max_fy, 
           " the most in any fiscal year since 2014."))
```

```{r, fig.keep=cond_ice_ero, results= res_ice_ero}
#| label: ICE ERO Removals and Returns
cat(paste0("ICE ERO Removals and Returns of " , str_to_title(params$ctzn), " Citizens by Fiscal Year"))
df <- out_ice_ero[[1]]
plt <- plot_df(df, params$ctzn, "ICE ERO Removals and Returns by FY", "Removals/Returns")
max <- unlist(out_ice_ero[[2]])
max_fy <- unlist(out_ice_ero[[3]])
plt
cat(paste0("ICE removed or returned ", scales::comma(max), 
           " citizens of ", str_to_title(params$ctzn), 
           " from the United States in ", max_fy, 
           " the most in any fiscal year since 2014."))
```